### ISSUE TITLE
AttributeError: 'OAuth2Credentials' object has no attribute 'invalid'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Dragon-Born/google-api-python-client#60]
```
This issue came about after upgrading from 1.0beta1-1-x86_64 to 1.0beta4-1-x86_6

What steps will reproduce the problem?
1. Write something that uses oauth2client/client.py
2. Run said program.

What is the expected output?
I expect an error not to be thrown.

What do you see instead?
End of the traceback:
File "/usr/lib/python2.7/site-packages/oauth2client/client.py", line 382, in 
_refresh
    if (new_cred and not new_cred.invalid and
AttributeError: 'OAuth2Credentials' object has no attribute 'invalid'


What version of the product are you using?
google-api-python-client-1.0beta4.tar.gz 

On what operating system?
Linux scott-laptop 3.0-ARCH #1 SMP PREEMPT Tue Aug 30 08:53:25 CEST 2011 x86_64 
Intel(R) Core(TM)2 Duo CPU T5750 @ 2.00GHz GenuineIntel GNU/Linux

Please provide any additional information below.
Summary: I upgraded from version 1.0beta1-1-x86_64 to 1.0beta4-1-x86_64 and now 
the OAuth2Credentials object doesn't seem to have a 'invalid' attribute but 
it's still being used in the libraries internal code as well as examples I've 
found on Google's documentation/help pages.
```

Original issue reported on code.google.com by `GoldCo...@gmail.com` on 22 Sep 2011 at 2:16

**Comment by GoogleCodeExporter** [comment]
Original comment by `jcgregorio@google.com` on 1 Aug 2012 at 6:45
- Changed state: **Closed**
